### ISSUE TITLE
https://game.ecn.fit/sheep 突然玩不了了

### ISSUE THREAD

**Issue by sysdefault** [SleepyAsh0191/sheep-n-sheep-backend#10]
https://game.ecn.fit/sheep 玩不了，这种状况有两三天了，点加入羊群没反应了，进不去游戏界面
![录屏_选择区域_20221003165340](https://user-images.githubusercontent.com/72608492/193538144-6fca7301-46c5-45ef-8288-971b4b638a5f.gif)

**Comment by SleepyAsh0191** [comment]
猪逼服主突然把后端给关了，马上修

**Comment by SleepyAsh0191** [comment]
已修复，若无法进入游戏，请清除缓存重试！

**Comment by sysdefault** [comment]
可以玩了
