### ISSUE TITLE
建议直接配置好打包参数

### ISSUE THREAD

**Issue by JulienZeng** [SleepyAsh0191/sheep-n-sheep-backend#2]
来自一个想白嫖jar包扔服务器的人的想法...
java没咋学，根本不会打包，构建出来的jar一堆报错...

**Comment by SleepyAsh0191** [comment]
请前往[Actions](https://github.com/SleepyAsh0191/sheep-n-sheep-backend/actions)自行下载

点击最新的一个commit，然后点击[Artifact](https://github.com/SleepyAsh0191/sheep-n-sheep-backend/suites/8307835064/artifacts/364635685)，然后解压。
