### ISSUE TITLE
能出个教程吗

### ISSUE THREAD

**Issue by qingci2024** [SleepyAsh0191/sheep-n-sheep-backend#3]
看了一下你的感觉还不错就是后端不会搭建前端我还会直接放进服务器就好了，这个后端真心不会弄

**Comment by SleepyAsh0191** [comment]
1. 请确保你安装了 Java
2. 如果不会编译的话，请前往[Actions](https://github.com/SleepyAsh0191/sheep-n-sheep-backend/actions)下载最新的构建
3. 前端需要修改js代码，可直接按照规则替换
4. 后端运行端口为8080，或自己修改端口 `在命令行的jar文件后面输入--server.port=xxxx`，如果想分配到子域名可进行反向代理。

**Comment by qingci2024** [comment]
行吧放弃了不会弄

**Comment by SleepyAsh0191** [comment]
如果我有时间的话 可能会出个教程吧。

**Comment by qingci2024** [comment]
行，我先用那套不需要后端的
