### ISSUE TITLE
大佬，后端和前端要怎么实现数据交互。

### ISSUE THREAD

**Issue by wang8456** [SleepyAsh0191/sheep-n-sheep-backend#4]
大佬，后端和前端要怎么实现数据交互。

**Comment by SleepyAsh0191** [comment]
![image](https://user-images.githubusercontent.com/64446140/190541884-6b6c3b63-4f6a-4d83-8cd2-c1c4444e1758.png)
前端，這裡的地址改一下
文件位于`assets/resources/index.8b75c.js`
