### ISSUE TITLE
老哥 你好

### ISSUE THREAD

**Issue by kuyoos** [SleepyAsh0191/sheep-n-sheep-backend#5]
官方接口又死了吗  我这用你的编译出jar运行没问题 还是进不去

**Comment by SleepyAsh0191** [comment]
官方崩了，可以尝试修改此处为`true`（yml可直接解压）
![image](https://user-images.githubusercontent.com/64446140/190565409-57ec6e34-2d37-4bed-b7d7-23f59635b6c5.png)
之后进游戏没有羊群为正常现象，游戏能照样进，官方把能获取开屏羊群的接口给换了

**Comment by kuyoos** [comment]
好像还是不好使

**Comment by kuyoos** [comment]
![image](https://user-images.githubusercontent.com/104617360/190566336-769c588a-9bd5-4990-92cf-d50e7359ccfc.png)抓包正常

**Comment by SleepyAsh0191** [comment]
可以截图下浏览器控制台吗（console）

管理接口被和谐了，晚些修

**Comment by SleepyAsh0191** [comment]
推送完毕，已经弃用官方地图api

**Comment by kuyoos** [comment]
好的  大哥  我问一下 启动方式就是直接命令吗 java -jar **.jar  不需要安装其他环境什么的吗

**Comment by SleepyAsh0191** [comment]
是，不需要配置启动方式，之后如果再获取不到地图的话，就可以尝试下直接改包里的map_data.json

**Comment by kuyoos** [comment]
![image](https://user-images.githubusercontent.com/104617360/190570718-365bbc9f-a71f-40b2-b8a2-2af28c79bb10.png)
老哥是不是和java环境有问题 我的是17要换成8吗

**Comment by kuyoos** [comment]
![image](https://user-images.githubusercontent.com/104617360/190571007-62ad803e-e52c-4df5-a40e-e57dc0158491.png)

**Comment by SleepyAsh0191** [comment]
可以方便加下QQ吗

**Comment by kuyoos** [comment]
30******24  谢谢哥

**Comment by SleepyAsh0191** [comment]
加了
